#!/bin/bash
# Git-based API Handler for bapXconnect
# Processes API requests stored as JSON files in the repository

# This script would be run as part of a GitHub Action

set -e

echo "Processing bapXconnect API requests..."

# Create or update the last processed file marker
touch .last_processed

# Loop through all request files that are newer than the last processed marker
for request_file in requests/*.json; do
  if [[ -f "$request_file" ]]; then
    echo "Processing request file: $request_file"
    
    # Extract the request ID and other parameters
    REQUEST_ID=$(jq -r '.id' "$request_file")
    MODEL=$(jq -r '.model' "$request_file")
    INPUT=$(jq -r '.input' "$request_file")
    PARAMETERS=$(jq -r '.parameters // {}' "$request_file")
    CORRELATION_ID=$(jq -r '.correlation_id // ""' "$request_file")
    
    # In a real implementation, this would connect to Hugging Face models
    # For now, we'll simulate a response
    RESPONSE_TEXT="This response was generated by processing your request through the bapXconnect API gateway.
    
Model used: $MODEL
Input: $INPUT
Parameters: $PARAMETERS

This demonstrates the API connection is active and working.
In the live implementation, this would return results from Hugging Face models."
    
    # Create response JSON
    RESPONSE_JSON=$(jq -n --arg req_id "$REQUEST_ID" --arg model "$MODEL" --arg text "$RESPONSE_TEXT" --arg corr_id "$CORRELATION_ID" '
    {
      id: ("resp_" + (now | tostring) + "_" + $req_id),
      request_id: $req_id,
      correlation_id: $corr_id,
      model: $model,
      output: { text: $text },
      usage: {
        prompt_tokens: ($text | length),
        completion_tokens: ($text | length),
        total_tokens: (($text | length) * 2),
        finish_reason: "stop"
      },
      created: (now | floor)
    }')
    
    # Write response to the responses directory
    echo "$RESPONSE_JSON" > "responses/response_$REQUEST_ID.json"
    
    # If correlation_id exists, update the session incrementally
    if [ "$CORRELATION_ID" != "" ] && [ "$CORRELATION_ID" != "null" ]; then
      SESSION_FILE="sessions/$CORRELATION_ID.json"
      
      # Create/update session file incrementally
      if [ -f "$SESSION_FILE" ]; then
        # Append to existing session
        TEMP_FILE=$(mktemp)
        jq --arg input "$INPUT" --arg response "$RESPONSE_TEXT" '
          .updated_at = (now | floor) |
          .messages += [
            {role: "user", content: $input},
            {role: "assistant", content: $response}
          ]
        ' "$SESSION_FILE" > "$TEMP_FILE" && mv "$TEMP_FILE" "$SESSION_FILE"
      else
        # Create new session
        SESSION_JSON=$(jq -n --arg id "$CORRELATION_ID" --arg input "$INPUT" --arg response "$RESPONSE_TEXT" '
        {
          session_id: $id,
          created_at: (now | floor),
          updated_at: (now | floor),
          messages: [
            {role: "user", content: $input},
            {role: "assistant", content: $response}
          ]
        }')
        
        echo "$SESSION_JSON" > "$SESSION_FILE"
      fi
    fi
    
    # Mark this request as processed by renaming it
    mv "$request_file" "$request_file.processed"
  fi
done

echo "Processing complete. Responses and sessions updated."